services:
  # --- AIRFLOW ---
  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: stock-airflow-init
    user: root
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password123@postgres:5432/stock_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=my_super_secret_key_123
      - PYTHONPATH=/opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/stock_project
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "
        chmod 666 /var/run/docker.sock &&
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com
      "
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: stock-airflow-webserver
    restart: always
    user: root
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password123@postgres:5432/stock_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=my_super_secret_key_123
      - PYTHONPATH=/opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/stock_project
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"
    command: >
      bash -c "
        chmod 666 /var/run/docker.sock &&
        airflow webserver
      "
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: stock-airflow-scheduler
    restart: always
    user: root
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password123@postgres:5432/stock_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=my_super_secret_key_123
      - PYTHONPATH=/opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/stock_project
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "
        chmod 666 /var/run/docker.sock &&
        airflow scheduler
      "
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  # --- FRONTEND ---
  frontend:
    build: ./frontend
    container_name: stock-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  # --- BACKEND ---
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password123@postgres:5432/stock_db

  # --- MINIO ---
  minio:
    image: minio/minio
    container_name: stock-minio
    ports:
      - "9005:9000"
      - "9006:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  # --- POSTGRESQL ---
  postgres:
    image: postgres:15
    container_name: stock-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: stock_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "stock_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  # --- ZOOKEEPER ---
  zookeeper:
    image: bitnamilegacy/zookeeper:3.8.4
    container_name: stock-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # --- KAFKA ---
  kafka:
    image: bitnamilegacy/kafka:3.4.1
    container_name: stock-kafka
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper

  # --- SPARK ---
  spark-master:
    build: .
    container_name: stock-spark-master
    hostname: spark-master
    volumes:
      - ./:/opt/bitnami/spark/stock_project
    environment:
      - SPARK_MODE=master
      - PYTHONPATH=/opt/bitnami/spark:/opt/bitnami/spark/stock_project/spark_jobs
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    build: .
    container_name: stock-spark-worker
    hostname: spark-worker
    restart: on-failure
    volumes:
      - ./:/opt/bitnami/spark/stock_project
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - PYTHONPATH=/opt/bitnami/spark:/opt/bitnami/spark/stock_project/spark_jobs
    depends_on:
      - spark-master

  # --- KAFDROP ---
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: stock-kafdrop
    ports:
      - "9002:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - kafka
    restart: always

networks:
  default:
    name: stock-network

volumes:
  minio_data:
  postgres_data: